### ISSUE TITLE
Hello, how can I use this map for navigation? Can you open source this part of the code? Look forward to your reply, thank you!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [TempleRAIL/SOGMP#2]
Hello, how can I use this map for navigation? Can you open source this part of the code? Look forward to your reply, thank you!

**Comment by zzuxzt** [comment]
Thanks for your interest in our work. We have proposed a new software-optimized predictor and its navigation framework. I will open source all of this new prediction code and navigation code this month. I will let you know when I do.

**Comment by 3oo0q-kvmlskz** [comment]
Ok, look forward to your update, thank you very much!

**Comment by zzuxzt** [comment]
Update codes are available at [prediction code](https://github.com/TempleRAIL/scope) and [navigation code](https://github.com/TempleRAIL/scope_nav).
