### ISSUE TITLE
Hi, I recently read your paper Stochastic Occupancy Grid Map Prediction in Dynamic Scenes and I'm going to do something about it.  I take the liberty of asking this question, is it convenient for you to open source navigation code?  Thank you so much for your work!  Thank you!

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [TempleRAIL/SOGMP#4]
Hi, I recently read your paper Stochastic Occupancy Grid Map Prediction in
Dynamic Scenes and I'm going to do something about it.  I take the liberty of asking this question, is it convenient for you to open source navigation code?  Thank you so much for your work!  Thank you!

**Comment by zzuxzt** [comment]
Thanks for your interest in our work. We have proposed a new software-optimized predictor and its navigation framework. I will soon open source all of this new prediction code and navigation code on [scope_nav](https://github.com/TempleRAIL/scope_nav) repository, please keep an eye on it.
