### ISSUE TITLE
coordinate system

### ISSUE THREAD

**Issue by 3oo0q-kvmlskz** [TempleRAIL/SOGMP#8]
Hello, is the position in this data set oriented in the robot's local coordinate system? In global coordinates, in local coordinates what is the origin of the local coordinates?

**Comment by 3oo0q-kvmlskz** [comment]
Do linear and angular velocities differ with respect to the robot coordinate system and the global coordinate system?

**Comment by zzuxzt** [comment]
Position data is the position of the robot in the global coordinate.

Yes, while velocities represent the same physical motion, their components may look different when described in the robot's local frame versus the global frame due to changes in the robot's orientation and motion.
